import type { Device, Responder, DemoScenario, EmergencyEvent } from '../types';

export const DEMO_DEVICES: Device[] = [
  {
    id: 'AEGIS-CAM-001',
    name: 'Main Entrance',
    type: 'camera',
    location: { lat: 12.9716, lon: 77.5946, label: 'Main Entrance Gate' },
    status: 'streaming',
    isStreaming: true,
    lastSeen: new Date(),
    fps: 30,
    resolution: '1920x1080',
  },
  {
    id: 'AEGIS-CAM-002',
    name: 'Parking Area North',
    type: 'camera',
    location: { lat: 12.9724, lon: 77.5952, label: 'Parking Area North' },
    status: 'online',
    isStreaming: false,
    lastSeen: new Date(Date.now() - 60000),
    fps: 25,
    resolution: '1280x720',
  },
  {
    id: 'AEGIS-CAM-003',
    name: 'Campus Corridor B',
    type: 'camera',
    location: { lat: 12.9710, lon: 77.5940, label: 'Corridor B – Building 3' },
    status: 'streaming',
    isStreaming: true,
    lastSeen: new Date(),
    fps: 30,
    resolution: '1920x1080',
  },
  {
    id: 'AEGIS-CAM-004',
    name: 'Remote Service Road',
    type: 'camera',
    location: { lat: 12.9698, lon: 77.5930, label: 'Remote Service Road – West' },
    status: 'online',
    isStreaming: true,
    lastSeen: new Date(),
    fps: 15,
    resolution: '1280x720',
  },
  {
    id: 'AEGIS-CAM-005',
    name: 'Sports Area',
    type: 'camera',
    location: { lat: 12.9730, lon: 77.5960, label: 'Sports Ground – East' },
    status: 'offline',
    isStreaming: false,
    lastSeen: new Date(Date.now() - 3600000),
  },
  {
    id: 'AEGIS-CAM-006',
    name: 'Animal Care Area',
    type: 'camera',
    location: { lat: 12.9705, lon: 77.5965, label: 'Animal Care Facility' },
    status: 'streaming',
    isStreaming: true,
    lastSeen: new Date(),
    fps: 20,
    resolution: '1280x720',
    hasThermal: false,
  },
];

export const DEMO_RESPONDERS: Responder[] = [
  {
    id: 'RESP-SEC-01',
    name: 'Campus Security Alpha',
    type: 'security',
    location: { lat: 12.9720, lon: 77.5948, label: 'Security Post – Main Gate' },
    status: 'available',
    distance: 180,
  },
  {
    id: 'RESP-SEC-02',
    name: 'Campus Security Beta',
    type: 'security',
    location: { lat: 12.9712, lon: 77.5944, label: 'Security Post – North Block' },
    status: 'available',
    distance: 320,
  },
  {
    id: 'RESP-MED-01',
    name: 'Medical Response Unit',
    type: 'medical',
    location: { lat: 12.9718, lon: 77.5950, label: 'Medical Centre' },
    status: 'available',
    distance: 250,
  },
  {
    id: 'RESP-FIRE-01',
    name: 'Fire Safety Team',
    type: 'fire',
    location: { lat: 12.9725, lon: 77.5955, label: 'Fire Station – Campus' },
    status: 'available',
    distance: 400,
  },
  {
    id: 'RESP-ANIMAL-01',
    name: 'Animal Rescue Unit',
    type: 'animal_rescue',
    location: { lat: 12.9707, lon: 77.5963, label: 'Animal Welfare Office' },
    status: 'available',
    distance: 450,
  },
];

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'human_fall',
    name: 'Human Fall',
    description: 'AI detects and verifies a possible person fall.',
    category: 'Human Safety',
    duration: 35000,
    steps: [
      { time: 0, action: 'SET_STATE', label: 'CAMERA MONITORING', payload: { fallState: 'NORMAL', deviceId: 'AEGIS-CAM-001' } },
      { time: 2500, action: 'SET_STATE', label: 'PERSON DETECTED', payload: { fallState: 'PERSON_DETECTED' } },
      { time: 5000, action: 'SET_STATE', label: 'MOVEMENT ANALYSIS', payload: { fallState: 'MOVING' } },
      { time: 7500, action: 'SET_STATE', label: 'FALL DETECTED', payload: { fallState: 'POSSIBLE_FALL' } },
      { time: 9000, action: 'SET_STATE', label: 'VERIFYING', payload: { fallState: 'VERIFYING' } },
      { time: 19000, action: 'CONFIRM_EMERGENCY', label: 'EMERGENCY CONFIRMED', payload: { type: 'PERSON_FALL', severity: 'HIGH', deviceId: 'AEGIS-CAM-001' } },
      { time: 21500, action: 'ALERT_RESPONDER', label: 'RESPONDER ALERTED', payload: { responderId: 'RESP-SEC-01' } },
    ],
  },
  {
    id: 'remote_fall',
    name: 'Remote Area Fall',
    description: 'Demonstrates emergency detection where no one is nearby.',
    category: 'Human Safety',
    recommended: true,
    duration: 45000,
    steps: [
      { time: 0, action: 'SET_STATE', label: 'REMOTE SERVICE ROAD — MONITORING', payload: { fallState: 'NORMAL', deviceId: 'AEGIS-CAM-004' } },
      { time: 4000, action: 'SET_STATE', label: 'PERSON DETECTED', payload: { fallState: 'PERSON_DETECTED' } },
      { time: 6500, action: 'SET_STATE', label: 'MOVEMENT ANALYSIS', payload: { fallState: 'MOVING' } },
      { time: 9000, action: 'SET_STATE', label: 'FALL DETECTED', payload: { fallState: 'POSSIBLE_FALL' } },
      { time: 10500, action: 'SET_STATE', label: 'VERIFYING', payload: { fallState: 'VERIFYING' } },
      { time: 20500, action: 'CONFIRM_EMERGENCY', label: 'EMERGENCY CONFIRMED', payload: { type: 'PERSON_FALL', severity: 'HIGH', deviceId: 'AEGIS-CAM-004' } },
      { time: 23000, action: 'ALERT_RESPONDER', label: 'NEAREST REGISTERED RESPONDER ALERTED', payload: { responderId: 'RESP-SEC-01' } },
    ],
  },
  {
    id: 'fire_thermal',
    name: 'Fire + Thermal',
    description: 'Combines visual fire detection with thermal context.',
    category: 'Hazard Detection',
    duration: 30000,
    steps: [
      { time: 0, action: 'SET_STATE', label: 'RGB CAMERA MONITORING', payload: { fallState: 'NORMAL', deviceId: 'AEGIS-CAM-003' } },
      { time: 2500, action: 'FIRE_DETECTED', label: 'FIRE / SMOKE DETECTED', payload: { fireConfidence: 0.88 } },
      { time: 5000, action: 'THERMAL_HOTSPOT', label: 'THERMAL HOTSPOT DETECTED', payload: { thermalHotspot: true } },
      { time: 7500, action: 'CONFIRM_EMERGENCY', label: 'RGB + THERMAL AI FUSION — CRITICAL', payload: { type: 'FIRE', severity: 'CRITICAL', deviceId: 'AEGIS-CAM-003' } },
      { time: 9500, action: 'ALERT_RESPONDER', label: 'FIRE RESCUE DISPATCHED', payload: { responderId: 'RESP-FIRE-01' } },
    ],
  },
  {
    id: 'animal_distress',
    name: 'Animal Distress',
    description: 'Monitors animal posture, movement and persistent immobility.',
    category: 'Wildlife / Campus',
    duration: 35000,
    steps: [
      { time: 0, action: 'SET_STATE', label: 'CAMERA MONITORING', payload: { fallState: 'NORMAL', deviceId: 'AEGIS-CAM-006' } },
      { time: 2500, action: 'ANIMAL_DETECTED', label: 'ANIMAL DETECTED', payload: {} },
      { time: 5500, action: 'ANIMAL_IMMOBILE', label: 'POSTURE ANALYSIS — LOW MOVEMENT', payload: {} },
      { time: 9000, action: 'ANIMAL_IMMOBILE', label: 'PERSISTENT IMMOBILITY', payload: {} },
      { time: 13000, action: 'CONFIRM_EMERGENCY', label: 'POSSIBLE ANIMAL DISTRESS', payload: { type: 'ANIMAL_DISTRESS', severity: 'MEDIUM', deviceId: 'AEGIS-CAM-006' } },
      { time: 15500, action: 'ALERT_RESPONDER', label: 'ANIMAL RESPONDER ALERT', payload: { responderId: 'RESP-ANIMAL-01' } },
    ],
  },
  {
    id: 'campus_incident',
    name: 'Populated Campus',
    description: 'Monitors multiple subjects and distinguishes a fall anomaly from normal crowd activity.',
    category: 'Public Safety',
    duration: 40000,
    steps: [
      { time: 0, action: 'MULTI_OBJECT', label: 'MULTI-OBJECT MONITORING', payload: {} },
      { time: 5000, action: 'SET_STATE', label: 'ABNORMAL EVENT: PERSON FALL', payload: { fallState: 'POSSIBLE_FALL', deviceId: 'AEGIS-CAM-001' } },
      { time: 6500, action: 'SET_STATE', label: 'VERIFYING', payload: { fallState: 'VERIFYING' } },
      { time: 16500, action: 'CONFIRM_EMERGENCY', label: 'EMERGENCY CONFIRMED', payload: { type: 'PERSON_FALL', severity: 'HIGH', deviceId: 'AEGIS-CAM-001' } },
      { time: 19000, action: 'ALERT_RESPONDER', label: 'SECURITY ALERTED', payload: { responderId: 'RESP-SEC-02' } },
    ],
  },
  {
    id: 'multi_camera',
    name: 'Multi-Camera Incident',
    description: 'Demonstrates distributed camera network where one camera triggers emergency while others remain normal.',
    category: 'Infrastructure',
    duration: 35000,
    steps: [
      { time: 0, action: 'MULTI_CAMERA_STATUS', label: 'ALL CAMERAS MONITORING', payload: {} },
      { time: 4000, action: 'SET_STATE', label: 'ANOMALY ON CAM-04', payload: { fallState: 'POSSIBLE_FALL', deviceId: 'AEGIS-CAM-004' } },
      { time: 5500, action: 'SET_STATE', label: 'VERIFYING CAM-04', payload: { fallState: 'VERIFYING', deviceId: 'AEGIS-CAM-004' } },
      { time: 15500, action: 'CONFIRM_EMERGENCY', label: 'CAM-04 EMERGENCY CONFIRMED', payload: { type: 'PERSON_FALL', severity: 'HIGH', deviceId: 'AEGIS-CAM-004' } },
      { time: 17500, action: 'ALERT_RESPONDER', label: 'NEAREST RESPONDER ALERTED', payload: { responderId: 'RESP-SEC-01' } },
    ],
  },
];

export const DEMO_LOCATION_MAP: Record<string, { lat: number; lon: number; label: string }> = {
  'AEGIS-CAM-001': { lat: 12.9716, lon: 77.5946, label: 'Main Entrance Gate' },
  'AEGIS-CAM-002': { lat: 12.9724, lon: 77.5952, label: 'Parking Area North' },
  'AEGIS-CAM-003': { lat: 12.9710, lon: 77.5940, label: 'Corridor B – Building 3' },
  'AEGIS-CAM-004': { lat: 12.9698, lon: 77.5930, label: 'Remote Service Road – West' },
  'AEGIS-CAM-005': { lat: 12.9730, lon: 77.5960, label: 'Sports Ground – East' },
  'AEGIS-CAM-006': { lat: 12.9705, lon: 77.5965, label: 'Animal Care Facility' },
};
